More robust stipple bitmaps for fill indicator via indent-bars, do not use oh-my-posh under tramp.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,10 +7,10 @@
 #
 # Author: Danylo Malyuta, 2020.
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 if [ "$(pwd)" != "$DIR" ]; then
-   >&2 echo "ERROR: please run ./install from the root of the dotfiles repo."
-   exit 1
+    >&2 echo "ERROR: please run ./install from the root of the dotfiles repo."
+    exit 1
 fi
 
 # ..:: Copy dotfiles to home directory ::..
@@ -22,7 +22,7 @@ ln -sf "$DIR"/.local.bashrc ~
 
 # Various executable scripts
 if [ ! -f ./.bin/colorizer/Library/colorizer.sh ]; then
-   git submodule update --init --recursive
+    git submodule update --init --recursive
 fi
 ln -sf "$DIR"/.bin ~
 
@@ -44,11 +44,14 @@ mkdir -p ~/.ipython/profile_default/startup
 cp -r "$DIR"/.jupyter ~
 ln -sf "$DIR"/.config/flake8 ~/.config
 ln -sf "$DIR"/.ipython/profile_default/startup/fzf_history.py \
-   ~/.ipython/profile_default/startup
+    ~/.ipython/profile_default/startup
 
 # Julia
 mkdir -p ~/.julia/config
 ln -sf "$DIR"/.config/startup.jl ~/.julia/config
+
+# Prompt
+ln -sf "$DIR"/.config/.blue-owl-custom.omp.json ~/.blue-owl-custom.omp.json
 
 # ..:: Install modules ::..
 
